/**
 * Generates the component reference in docs/components/ from the catalog and
 * the playground's examples, so the docs can't drift from what the renderer
 * accepts. The other pages in docs/ are hand-written.
 *
 *   npm run docs
 */
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { componentDefinitions } from "../src/catalog";
import { compileWireframe, formatIssues } from "../src/compile";
import { iconNames } from "../src/icons";
import { componentDocs } from "../src/prompt";
import { renderWireframePng } from "../src/render";
import { bareWords } from "../src/text";
import { createRequire } from "node:module";

const LUCIDE_VERSION: string = createRequire(import.meta.url)("lucide/package.json").version;
import { EXAMPLES, GROUPS } from "../src/playground/reference";

const docsDir = path.dirname(fileURLToPath(import.meta.url));
const out = path.join(docsDir, "components");

/** Common UI icons for the picture on the icons page. Every name must exist in Lucide. */
const ICON_GROUPS: Record<string, string[]> = {
  Navigation: ["menu", "x", "arrow-left", "arrow-right", "chevron-left", "chevron-right", "chevron-down", "chevron-up", "house", "search", "ellipsis", "ellipsis-vertical", "external-link"],
  Actions: ["plus", "pencil", "trash-2", "copy", "share", "download", "upload", "send", "save", "refresh-cw", "funnel", "settings", "log-in", "log-out"],
  Status: ["check", "circle-check", "circle-alert", "triangle-alert", "info", "circle-help", "loader", "lock", "eye", "eye-off"],
  "People & messages": ["user", "users", "bell", "mail", "message-circle", "phone", "calendar", "clock", "map-pin", "heart", "star", "bookmark"],
  "Media & files": ["image", "camera", "file", "folder", "paperclip", "play", "pause", "music", "video", "mic"],
  Commerce: ["shopping-cart", "credit-card", "tag", "gift", "wallet", "receipt", "package", "truck"],
  Data: ["chart-bar", "chart-line", "trending-up", "table", "list", "layout-grid", "database"],
};

/** The icon sheet is itself a tsquare board: one screen per group, a grid of icons with their names. */
function iconSheet() {
  const cols = 5;
  const screens = Object.entries(ICON_GROUPS).map(([group, names]) => {
    const rows = Math.ceil(names.length / cols);
    const cells = names.map((n) => `      stack gap=8 align=center
        icon ${n} size=24
        text "${n}" sm muted`).join("\n");
    return `  screen custom "${group}" width=620 height=${rows * 62 + 30}\n    grid columns=${cols} gap=8\n${cells}`;
  });
  return `board grid columns=2 "Common icons"\n${screens.join("\n")}\n`;
}

async function writeIconsPage() {
  const sheet = iconSheet();
  const { spec, issues } = compileWireframe(sheet);
  if (!spec || issues.length) throw new Error(`icon sheet:\n${formatIssues(issues)}`);
  writeFileSync(path.join(docsDir, "icons.png"), await renderWireframePng(spec, { skipValidation: true, scale: 1.5 }));

  const names = [...new Set(iconNames)].sort();
  const byLetter = new Map<string, string[]>();
  for (const n of names) byLetter.set(n[0], [...(byLetter.get(n[0]) ?? []), n]);
  const page = `# Icons

Icons come from [Lucide](https://lucide.dev/icons) (ISC license), an open-source set of line icons. Use any Lucide name in kebab-case:

\`\`\`tsquare
    icon search
    button "Download" leadingIcon=download
    navbar "Inbox" actions=[search, ellipsis-vertical]
    tabbar items=[{label=Home icon=house}, {label=Cart icon=shopping-cart}]
\`\`\`

Lucide's older names work too, such as \`home\` for \`house\`. An unknown name is an error with close matches, so it never renders as a blank:

\`\`\`
line 3: Icon: unknown icon "serach" (did you mean search?)
\`\`\`

Suggestions come from spelling and shared words (\`cart\` → \`shopping-cart\`), not meaning: \`notification\` won't suggest \`bell\`. To find an icon by meaning, search [lucide.dev/icons](https://lucide.dev/icons), which also lets you search by tags.

## Common icons

![Common icons](icons.png)

## Every name

All ${names.length} names tsquare accepts (Lucide ${LUCIDE_VERSION}), generated by \`npm run docs\`. Use your browser's find to search.

${[...byLetter].map(([l, ns]) => `### ${l.toUpperCase()}\n\n${ns.map((n) => `\`${n}\``).join(" · ")}`).join("\n\n")}
`;
  writeFileSync(path.join(docsDir, "icons.md"), page);
}
const slug = (name: string) => name.toLowerCase();
const code = (s: string) => "`" + s + "`";
// "primary" | "secondary" → primary, secondary (pipes would break the Markdown table)
const values = (type: string) => type.replace(/"/g, "").replace(/ \| /g, ", ");
const list = (items: string[]) => items.map(code).join(", ");
const groupOf = (name: string) => GROUPS.find((g) => g.components.includes(name))!.name;

function writingIt(name: string, props: { name: string; main: boolean; type: string }[]) {
  const lines: string[] = [];
  const words = bareWords(name);
  const main = props.find((p) => p.main);
  if (main) {
    lines.push(
      words.wordPrimary
        ? `A word or quoted string sets **${main.name}**: ${code(`${slug(name)} search`)} or ${code(`${slug(name)} "arrow-left"`)}.`
        : `A quoted string sets **${main.name}**: ${code(`${slug(name)} "…"`)}.`,
    );
  }
  const byProp = new Map<string, string[]>();
  for (const { value, prop } of words.options) byProp.set(prop, [...(byProp.get(prop) ?? []), value]);
  for (const [prop, vals] of byProp) lines.push(`Bare words set **${prop}**: ${list(vals)}.`);
  if (words.ambiguous.length) {
    const owners = props.filter((p) => words.ambiguous.some((v) => values(p.type).split(", ").includes(v))).map((p) => p.name);
    const [v] = words.ambiguous;
    lines.push(
      `${list(words.ambiguous)} are options of ${owners.map((o) => `**${o}**`).join(" and ")}, so write which one you mean: ` +
        owners.map((o) => code(`${o}=${v}`)).join(" or ") + ".",
    );
  }
  for (const b of words.booleans) {
    if (b === "on") lines.push(`${code("on")} and ${code("off")} switch it on and off.`);
    else if (b === "checked") lines.push(`${code("checked")} and ${code("unchecked")} set whether it's checked.`);
    else lines.push(`${code(b)} turns **${b}** on; ${code(`no-${b}`)} turns it off.`);
  }
  lines.push("Anything else is written " + code("key=value") + ".");
  const slots = (componentDefinitions as Record<string, { slots: string[] }>)[name].slots;
  lines.push(slots.length ? "Holds other elements: indent them two spaces below it." : "Has no children.");
  return lines.map((l) => `- ${l}`).join("\n");
}

async function main() {
  rmSync(out, { recursive: true, force: true });
  mkdirSync(path.join(out, "images"), { recursive: true });
  const docs = componentDocs();

  for (const c of docs) {
    const example = EXAMPLES[c.name];
    const { spec, issues } = compileWireframe(example);
    if (!spec || issues.length) throw new Error(`${c.name} example:\n${formatIssues(issues)}`);
    writeFileSync(path.join(out, "images", `${slug(c.name)}.png`), await renderWireframePng(spec, { skipValidation: true, scale: 2 }));

    const rows = c.props.map((p) => {
      const tags = [p.main && "main text", p.required && "required"].filter(Boolean).join(", ");
      return `| ${code(p.name)}${tags ? ` *(${tags})*` : ""} | ${values(p.type)} | ${p.description ?? ""} |`;
    });
    const page = `# ${c.name}

${code(slug(c.name))} · ${groupOf(c.name)} · [All components](README.md)

${c.description}

![${c.name} example](images/${slug(c.name)}.png)

\`\`\`tsquare
${example.trimEnd()}
\`\`\`

## Writing it

${writingIt(c.name, c.props)}${c.props.some((p) => /Lucide/.test(p.description ?? "")) ? "\n\nIcon names: see [Icons](../icons.md) for the common ones and every name." : ""}

## Props

| Prop | Values | Notes |
|---|---|---|
${rows.join("\n")}
`;
    writeFileSync(path.join(out, `${slug(c.name)}.md`), page);
  }

  const index = `# Components

Every component, grouped as in the playground. Each page has a rendered example, its source, how to write it, and its props. These pages are generated from the catalog by \`npm run docs\`.

${GROUPS.map((g) => `## ${g.name}

| Component | What it's for |
|---|---|
${g.components.map((n) => `| [${slug(n)}](${slug(n)}.md) | ${docs.find((d) => d.name === n)!.description} |`).join("\n")}`).join("\n\n")}
`;
  writeFileSync(path.join(out, "README.md"), index);
  await writeIconsPage();
  console.log(`wrote ${docs.length} component pages to ${path.relative(process.cwd(), out)}`);
}

main();
